### ISSUE TITLE
Part 3: Error in spacy.load('en')

### ISSUE THREAD

**Issue by sanyabt** [dbmi-pitt/SocialMediaDataScience#3]
I am trying to run the code in Part 3 of the Jupyter Notebooks, however the spacy module is not loading in JupyterHub. I have confirmed that the Python version is 3.6. I get the error when trying to run this line

import spacy
nlp = spacy.load('en')

Attached screenshot of error.

Is anyone else getting this too?
<img width="895" alt="screen shot 2018-10-20 at 8 11 37 pm" src="https://user-images.githubusercontent.com/14127589/47261752-78ba4b00-d4a4-11e8-8837-332ac1020342.png">

**Comment by sanyabt** [comment]
Seems like its an error due to not loading the module. Fixed it by using my system and installing spacy and the module separately.
pip install spacy && python -m spacy download en

**Comment by harryhoch** [comment]
configuration issue on Pitt servers.

**Comment by mbayer-pitt** [comment]
here is another solution if you still have issues with 
_import spacy
nlp = spacy.load('en')_

replace them with 
**import en_core_web_sm
nlp = en_core_web_sm.load()**

here is where I found it: (https://spacy.io/usage/models)

**Comment by harryhoch** [comment]
Thanks!
