### ISSUE TITLE
git commands not working in https://hub.crc.pitt.edu

### ISSUE THREAD

**Issue by pritikadasgupta** [dbmi-pitt/SocialMediaDataScience#5]
Several students have run into this problem where they have succeeded in cloning the repository but they cannot clone or use git commands. I have replicated this issue in all three possible servers found in the CRC:

```
[prd17@legacy-n126 ~]$ git clone https://github.com/pritikadasgupta/SocialMediaDataScience.git
bash: git: command not found
```

**Comment by pritikadasgupta** [comment]
We talked with the CRC - git commands should work. However, some of the python packages are not loading in the hub.

If the packages aren't properly importing, we have created a document to help you set up your own environment on your system:
https://docs.google.com/document/d/1yM5DgCIjb6xyJb6RHMFZDo8m3Di-4uOXq0-reXZph34/edit

**Comment by harryhoch** [comment]
configuration issue on Pitt servers
